<a href="https://colab.research.google.com/github/Vaibhavrathore1999/ML-building-blocks/blob/main/Attention.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# All Four types of Attention

In [ ]:
import torch
inputs = torch.tensor(
        [[0.43, 0.15, 0.89], # Your (x^1)
        [0.55, 0.87, 0.66], # journey (x^2)
        [0.57, 0.85, 0.64], # starts (x^3)
        [0.22, 0.58, 0.33], # with (x^4)
        [0.77, 0.25, 0.10], # one (x^5)
        [0.05, 0.80, 0.55]] # step (x^6)
        )
print(inputs.shape)

torch.Size([6, 3])


In [ ]:
query=inputs[1]
attn_scores_2=torch.empty(inputs.shape[0])
print(attn_scores_2)

tensor([ 0.0000e+00,  0.0000e+00,  1.5835e-43,  0.0000e+00, -1.1531e+01,
         4.4844e-41])


In [ ]:
def softmax(x):
  return torch.tensor([torch.exp(elem)/torch.sum(torch.exp(x),dim=0) for elem in x])

In [ ]:
softmax(attn_scores_2)

tensor([2.0000e-01, 2.0000e-01, 2.0000e-01, 2.0000e-01, 1.9650e-06, 2.0000e-01])

# Simplified Self-Attention

In [ ]:
for i ,x_i in enumerate(inputs):
  attn_scores_2[i]=torch.dot(query,x_i)
print(attn_scores_2)

attn_scores_2_normalized=torch.softmax(attn_scores_2,dim=0)
print(attn_scores_2_normalized)

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])
tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])


In [ ]:
query=inputs[1]
context_vector_2=torch.zeros(query.shape[0])

for i,x_i in enumerate(inputs):
  context_vector_2+=x_i*attn_scores_2_normalized[i]
print(context_vector_2)

tensor([0.4419, 0.6515, 0.5683])


In [ ]:
print(inputs.shape)

torch.Size([6, 3])


Attention Matrix will be (words,words) here (6,6)

In [ ]:
attn_matrix=torch.zeros(inputs.shape[0],inputs.shape[0])
for i in range(inputs.shape[0]):
  for j in range(inputs.shape[0]):
    attn_matrix[i,j]=torch.dot(inputs[i],inputs[j])
print(attn_matrix)

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])


In [ ]:
attn_matrix_normalized=torch.softmax(attn_matrix,dim=0) #/torch.sqrt(torch.tensor(inputs.shape[1]))
print(attn_matrix_normalized)

tensor([[0.2098, 0.1385, 0.1390, 0.1435, 0.1526, 0.1385],
        [0.2006, 0.2379, 0.2369, 0.2074, 0.1958, 0.2184],
        [0.1981, 0.2333, 0.2326, 0.2046, 0.1975, 0.2128],
        [0.1242, 0.1240, 0.1242, 0.1462, 0.1367, 0.1420],
        [0.1220, 0.1082, 0.1108, 0.1263, 0.1879, 0.0988],
        [0.1452, 0.1581, 0.1565, 0.1720, 0.1295, 0.1896]])


In [ ]:
attn_scores=inputs@inputs.T
print(attn_scores)

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])


In [ ]:
print(attn_scores.shape)

torch.Size([6, 6])


In [ ]:
attn_weights = torch.softmax(attn_scores, dim=-1)
print(attn_weights)

tensor([[0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452],
        [0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581],
        [0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565],
        [0.1435, 0.2074, 0.2046, 0.1462, 0.1263, 0.1720],
        [0.1526, 0.1958, 0.1975, 0.1367, 0.1879, 0.1295],
        [0.1385, 0.2184, 0.2128, 0.1420, 0.0988, 0.1896]])


In [ ]:
s_=torch.sum(attn_weights,dim=1)
print(s_)

tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000])


In [ ]:
context_vectors=attn_weights@inputs

In [ ]:
print(context_vectors)

tensor([[0.4421, 0.5931, 0.5790],
        [0.4419, 0.6515, 0.5683],
        [0.4431, 0.6496, 0.5671],
        [0.4304, 0.6298, 0.5510],
        [0.4671, 0.5910, 0.5266],
        [0.4177, 0.6503, 0.5645]])


# Self-Attention

In [ ]:
torch.manual_seed(123)
x_2=inputs[1]
print(x_2)
d_in=x_2.shape[0]
d_out=2
print(d_in)
W_q=torch.randn(d_in,d_out)
W_k=torch.randn(d_in,d_out)
W_v=torch.randn(d_in,d_out)

query_2=x_2@W_q
print(query_2)
key_2=x_2@W_k
print(key_2)
value_2=x_2@W_v
print(value_2)

tensor([0.5500, 0.8700, 0.6600])
3
tensor([-1.1729, -0.0048])
tensor([-0.1142, -0.7676])
tensor([0.4107, 0.6274])


In [ ]:
import torch.nn as nn
W_q=nn.Parameter(W_q)
W_k=nn.Parameter(W_k)
W_v=nn.Parameter(W_v)

In [ ]:
query=inputs@W_q
key=inputs@W_k
value=inputs@W_v
print(query)
print(key)
print(value)

tensor([[-1.1686,  0.2019],
        [-1.1729, -0.0048],
        [-1.1438, -0.0018],
        [-0.6339, -0.0439],
        [-0.2979,  0.0535],
        [-0.9596, -0.0712]], grad_fn=<MmBackward0>)
tensor([[-0.1823, -0.6888],
        [-0.1142, -0.7676],
        [-0.1443, -0.7728],
        [ 0.0434, -0.3580],
        [-0.6467, -0.6476],
        [ 0.3262, -0.3395]], grad_fn=<MmBackward0>)
tensor([[ 0.1196, -0.3566],
        [ 0.4107,  0.6274],
        [ 0.4091,  0.6390],
        [ 0.2436,  0.4182],
        [ 0.2653,  0.6668],
        [ 0.2728,  0.3242]], grad_fn=<MmBackward0>)


In [ ]:
print(W_k.requires_grad)
print(W_q.requires_grad)
print(W_v.requires_grad)

True
True
True


In [ ]:
print(query.shape)
print(key.shape)
print(value.shape)
attn_matrix_trainable=query@key.T
print(attn_matrix_trainable)
print(attn_matrix_trainable.shape)

torch.Size([6, 2])
torch.Size([6, 2])
torch.Size([6, 2])
tensor([[ 0.0740, -0.0216,  0.0126, -0.1230,  0.6250, -0.4498],
        [ 0.2172,  0.1376,  0.1730, -0.0491,  0.7616, -0.3809],
        [ 0.2098,  0.1320,  0.1665, -0.0489,  0.7408, -0.3725],
        [ 0.1458,  0.1061,  0.1254, -0.0118,  0.4384, -0.1919],
        [ 0.0175, -0.0071,  0.0017, -0.0321,  0.1580, -0.1153],
        [ 0.2240,  0.1642,  0.1935, -0.0161,  0.6667, -0.2888]],
       grad_fn=<MmBackward0>)
torch.Size([6, 6])


In [ ]:
attn_matrix_trainable=torch.softmax(attn_matrix_trainable/(torch.sqrt(torch.tensor(d_out))),dim=1)
print(attn_matrix_trainable)

tensor([[0.1687, 0.1576, 0.1615, 0.1467, 0.2490, 0.1165],
        [0.1704, 0.1611, 0.1652, 0.1412, 0.2505, 0.1117],
        [0.1704, 0.1613, 0.1653, 0.1419, 0.2481, 0.1129],
        [0.1704, 0.1656, 0.1679, 0.1524, 0.2095, 0.1342],
        [0.1680, 0.1651, 0.1661, 0.1622, 0.1856, 0.1529],
        [0.1711, 0.1640, 0.1675, 0.1444, 0.2340, 0.1191]],
       grad_fn=<SoftmaxBackward0>)


In [ ]:
context_vectors_attended=attn_matrix_trainable@value
print(context_vectors_attended)

tensor([[0.2845, 0.4071],
        [0.2854, 0.4081],
        [0.2854, 0.4075],
        [0.2864, 0.3974],
        [0.2863, 0.3910],
        [0.2860, 0.4039]], grad_fn=<MmBackward0>)


# Self-Attention Class

In [ ]:
import torch.nn as nn
class SelfAttention_v1(nn.Module):
  def __init__(self,d_in,d_out) -> None:
    super().__init__()
    self.d_out=d_out
    self.W_q=nn.Parameter(torch.randn(d_in,d_out))
    self.W_k=nn.Parameter(torch.randn(d_in,d_out))
    self.W_v=nn.Parameter(torch.randn(d_in,d_out))
  def forward(self,x):
    query=x@self.W_q
    key=x@self.W_k
    value=x@self.W_v
    attn_matrix=query@key.T
    attn_matrix==torch.softmax(attn_matrix/(self.d_out**(0.5)),dim=-1)
    context_vec=attn_matrix@value
    return context_vec


In [ ]:
attn=SelfAttention_v1(d_in=3,d_out=2)
print(attn)

SelfAttention_v1()


In [ ]:
context_vec=attn(inputs)
print(context_vec)

tensor([[ 0.3697,  0.6248],
        [ 0.0168, -0.3025],
        [ 0.0228, -0.2873],
        [-0.0655, -0.3330],
        [ 0.1244,  0.0671],
        [-0.1187, -0.4817]], grad_fn=<MmBackward0>)


In [ ]:
import torch.nn as nn
class SelfAttention_v2(nn.Module):
  def __init__(self,d_in,d_out,bias=False) -> None:
    super().__init__()
    self.W_q=nn.Linear(d_in,d_out,bias=bias)
    self.W_k=nn.Linear(d_in,d_out,bias=bias)
    self.W_v=nn.Linear(d_in,d_out,bias=bias)
  def forward(self,x):
    query=self.W_k(x)
    key=self.W_k(x)
    value=self.W_v(x)
    attn_matrix=query@key.T
    attn_matrix==torch.softmax(attn_matrix/(query.shape[-1]**(0.5)),dim=-1)
    context_vec=attn_matrix@value
    return context_vec


In [ ]:
attn_2=SelfAttention_v2(d_in=3,d_out=2,bias=True)
print(attn_2)

SelfAttention_v2(
  (W_q): Linear(in_features=3, out_features=2, bias=True)
  (W_k): Linear(in_features=3, out_features=2, bias=True)
  (W_v): Linear(in_features=3, out_features=2, bias=True)
)


In [ ]:
print(attn_2(inputs))

tensor([[-0.0647,  0.1916],
        [-0.0287,  0.0800],
        [-0.0298,  0.0836],
        [-0.0879,  0.2541],
        [-0.0847,  0.2551],
        [-0.0729,  0.2051]], grad_fn=<MmBackward0>)


In [ ]:
print(attn.W_k.shape)
print(attn_2.W_k.weight.shape)
attn_2.W_k.weight=nn.Parameter(attn.W_k.T)
attn_2_W_v=nn.Parameter(attn.W_v.T)
attn_2.W_q.weight=nn.Parameter(attn.W_q.T)

torch.Size([3, 2])
torch.Size([2, 3])


In [ ]:
print(attn_2(inputs))

tensor([[-0.8899,  2.6266],
        [-0.2916,  0.9041],
        [-0.3102,  0.9590],
        [-0.1318,  0.3699],
        [-0.6340,  1.8799],
        [ 0.0394, -0.1316]], grad_fn=<MmBackward0>)


# Causal Attention (Masked Attention)

In [ ]:
class CausalSelfAttention(nn.Module):
  def __init__(self,d_in,d_out):
    super().__init__()
    self.W_q=nn.Linear(d_in,d_out,bias=False)
    self.W_k=nn.Linear(d_in,d_out,bias=False)
    self.W_v=nn.Linear(d_in,d_out,bias=False)
  def forward(self,x):
    query=self.W_q(x)
    key=self.W_k(x)
    value=self.W_v(x)
    attn_matrix = query @ key.transpose(-2, -1)
    mask = torch.tril(torch.ones_like(attn_matrix))
    causal_attn_matrix=attn_matrix * mask
    casuall_attn_matrix=torch.softmax(causal_attn_matrix/(query.shape[-1]**(0.5)),dim=-1)
    context_vec=causal_attn_matrix@value
    return context_vec

In [ ]:
c_attn=CausalSelfAttention(d_in=3,d_out=2)
print(c_attn(inputs))

tensor([[ 0.0249, -0.0391],
        [ 0.1294, -0.0391],
        [ 0.2253, -0.0248],
        [ 0.1397, -0.0065],
        [ 0.1271, -0.0250],
        [ 0.2971,  0.0187]], grad_fn=<MmBackward0>)


# Dropout in Causal Attention

In [ ]:
dropout=torch.nn.Dropout(0.5)
example=torch.ones(6,6)
print(example)
print(dropout(example))

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])
tensor([[2., 0., 0., 0., 2., 0.],
        [2., 2., 2., 0., 2., 0.],
        [0., 2., 0., 0., 0., 0.],
        [2., 0., 0., 2., 2., 0.],
        [0., 2., 0., 0., 0., 0.],
        [0., 2., 2., 2., 0., 2.]])


In [ ]:
print(dropout(attn_matrix))

tensor([[1.9990, 0.0000, 0.0000, 0.0000, 0.9152, 0.0000],
        [0.0000, 2.9900, 2.9508, 1.6868, 1.4140, 2.1730],
        [0.0000, 0.0000, 2.9140, 0.0000, 0.0000, 2.1210],
        [0.0000, 1.6868, 1.6592, 0.9874, 0.6948, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 1.3308, 0.5870],
        [0.0000, 0.0000, 2.1210, 0.0000, 0.5870, 1.8900]])


In [ ]:
batch=torch.stack((inputs,inputs),dim=0)
print(batch.shape)

torch.Size([2, 6, 3])


In [ ]:
class CausalSelfAttention_v2(nn.Module):
  def __init__(self,d_in,d_out,dropout_value):
    super().__init__()
    self.W_q=nn.Linear(d_in,d_out,bias=False)
    self.W_k=nn.Linear(d_in,d_out,bias=False)
    self.W_v=nn.Linear(d_in,d_out,bias=False)
    self.dropout=torch.nn.Dropout(dropout_value)
  def forward(self,x):
    query=self.W_q(x)
    key=self.W_k(x)
    value=self.W_v(x)
    attn_matrix = query @ key.transpose(-2, -1)
    mask = torch.tril(torch.ones_like(attn_matrix))
    causal_attn_matrix=attn_matrix * mask
    casuall_attn_matrix=torch.softmax(causal_attn_matrix/(query.shape[-1]**(0.5)),dim=-1)
    casuall_attn_matrix=self.dropout(casuall_attn_matrix)
    context_vec=causal_attn_matrix@value
    return context_vec

In [ ]:
ca=CausalSelfAttention_v2(d_in=3,d_out=2,dropout_value=0.5)
print(ca(batch).shape)

torch.Size([2, 6, 2])


# MultiHead Self Attention

In [ ]:
class MultiHeadAttentionWrapper(nn.Module):
  def __init__(self,d_in,d_out,dropout_value,num_heads):
    super().__init__()
    self.heads=nn.ModuleList([CausalSelfAttention_v2(d_in,d_out,dropout_value) for _ in range(num_heads)])
    self.W_o=nn.Linear(d_out*num_heads,d_out)
  def forward(self,x):
    return torch.cat([head(x) for head in self.heads],dim=-1)       # Concatenated along columns horizontal extend ho jayega


In [ ]:
torch.manual_seed(123)
context_length = batch.shape[1] # This is the number of tokens
print(batch.shape)
d_in, d_out = 3, 2

torch.Size([2, 6, 3])


In [ ]:
mha=MultiHeadAttentionWrapper(d_in,d_out,0.5,8)
context_vecs = mha(batch)
print(context_vecs.shape)

torch.Size([2, 6, 16])


In [ ]:
class MultiHeadAttention(nn.Module):
  def __init__(self,d_in,d_out,n_heads,dropout):
    super().__init__()
    assert (d_out%n_heads==0) , "d_out must be divisible by num_heads"
    self.W_k=nn.Linear(d_in,d_out,bias=False)
    self.W_q=nn.Linear(d_in,d_out,bias=False)
    self.W_v=nn.Linear(d_in,d_out,bias=False)
    self.n_heads=n_heads
    self.head_dim=d_out//n_heads
    self.out_proj = nn.Linear(d_out, d_out)
    self.dropout=nn.Dropout(dropout)
  def forward(self,x):
    queries=self.W_q(x)          # Shape (batch,num_tokens,d_out)
    keys=self.W_k(x)            # Shape (batch,num_tokens,d_out)
    values=self.W_v(x)          # Shape (batch,num_tokens,d_out)
    keys=keys.view(keys.shape[0],keys.shape[1],self.n_heads,self.head_dim)                        # Shape (batch,num_tokens,n_heads,head_dim)
    queries=queries.view(queries.shape[0],queries.shape[1],self.n_heads,self.head_dim)            # Shape (batch,num_tokens,n_heads,head_dim)
    values=values.view(values.shape[0],values.shape[1],self.n_heads,self.head_dim)                # Shape (batch,num_tokens,n_heads,head_dim)
    keys=keys.transpose(1,2)                                                                    # Shape (batch,n_heads,num_tokens,head_dim)
    queries=queries.transpose(1,2)                                                              # Shape (batch,n_heads,num_tokens,head_dim)
    values=values.transpose(1,2)                                                                # Shape (batch,n_heads,num_tokens,head_dim)
    attn_matrix=queries@keys.transpose(-2,-1)                         # Shape (batch,n_heads,num_tokens,n_tokens)
    attn_matrix=attn_matrix/(self.head_dim**(0.5))
    mask=torch.tril(torch.ones_like(attn_matrix))
    attn_matrix=attn_matrix*mask
    attn_matrix=torch.softmax(attn_matrix,dim=-1)
    attn_matrix=self.dropout(attn_matrix)
    context_vec=(attn_matrix@values)                          # Shape (batch,n_heads,num_tokens,head_dim)
    context_vec=context_vec.transpose(1,2)                   # Shape (batch,num_tokens,n_heads,head_dim)
    context_vec=context_vec.contiguous().view(context_vec.shape[0],context_vec.shape[1],self.n_heads*self.head_dim) # Shape (batch,num_tokens,d_out)
    return self.out_proj(context_vec)


In [ ]:
torch.manual_seed(123)
batch_size, context_length, d_in = batch.shape
d_out = 2
mha = MultiHeadAttention(d_in, d_out,n_heads=2,dropout=0.5)
print(mha)
context_vecs = mha(batch)
print(context_vecs)
print("context_vecs.shape:", context_vecs.shape)

MultiHeadAttention(
  (W_k): Linear(in_features=3, out_features=2, bias=False)
  (W_q): Linear(in_features=3, out_features=2, bias=False)
  (W_v): Linear(in_features=3, out_features=2, bias=False)
  (out_proj): Linear(in_features=2, out_features=2, bias=True)
  (dropout): Dropout(p=0.5, inplace=False)
)
tensor([[[0.2612, 0.4112],
         [0.2502, 0.4808],
         [0.2525, 0.3365],
         [0.2361, 0.4074],
         [0.2865, 0.3215],
         [0.2815, 0.3406]],

        [[0.2427, 0.4002],
         [0.2255, 0.4704],
         [0.3056, 0.2625],
         [0.2032, 0.5170],
         [0.2207, 0.4779],
         [0.2960, 0.3486]]], grad_fn=<ViewBackward0>)
context_vecs.shape: torch.Size([2, 6, 2])
